// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrflgtvaplopyzykgwuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyZmxndHZhcGxvcHl6eWtnd3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk4NTAsImV4cCI6MjA2NTU4NTg1MH0.BpJqYapT2jRkhsEIuuBiJWYKScFc30oit6UOQNeD9tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);